name: Run JS Daily at 7AM KST

on:
  schedule:
    - cron: '0 22 * * *'  # 한국 오전 7시 = UTC 전날 22시
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (if needed)
        run: npm install

      - name: Run script
        run: node CloudService.js
