name: Daily CloudService Run

on:
  schedule:
    - cron: '0 22 * * *'   # 한국시간 07:00
  workflow_dispatch:

jobs:
  run-cloudservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm install

      - name: Install CloudType CLI
        run: npm install -g @cloudtype/cli

      - name: Run CloudService.js
        run: node ./main/CloudService.js
